version: '3.9'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  web:
    build: .
    # container_name: jaydenooi28Django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16.4
    container_name: db
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=firstdb
    ports:
      - "5432:5432"


# volumes:
#   postgres_data: